In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [37]:
df=pd.read_csv("/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv")

In [38]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [39]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [41]:
df.duplicated().sum()

0

In [42]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [43]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [44]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [45]:
df.drop(columns=['RowNumber','Surname', 'CustomerId' ], inplace= True , axis=1)

In [46]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [47]:
df=pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [48]:
x=df.drop(columns=['Exited'])
y= df['Exited']

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
xtrain , xtest , ytrain , ytest = train_test_split(x,y , test_size=0.2 , random_state=22)

In [51]:
xtrain

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
3821,608,56,5,0.00,2,0,1,153810.41,False,True,False
6136,780,33,6,145580.61,1,1,1,154598.56,False,True,False
8161,588,31,4,99607.37,2,0,1,35877.03,False,False,True
655,498,25,8,121702.73,1,1,1,132210.49,True,False,True
2950,734,37,0,152760.24,1,1,1,48990.50,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
4587,500,34,6,0.00,1,1,1,140268.45,False,False,False
6646,685,42,2,0.00,2,0,0,199992.48,False,True,False
5478,648,44,9,111369.79,2,1,1,91947.74,True,False,True
8548,517,46,4,0.00,1,1,0,22372.78,False,True,True
6276,554,54,6,108755.00,1,1,0,40914.32,True,False,False

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
scaler= StandardScaler()

In [54]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.fit_transform(xtest)

In [55]:
xtrain_scaled

array([[-4.38199762e-01,  1.63434970e+00,  1.42695060e-03, ...,
        -5.83123916e-01,  1.74895780e+00, -1.09831140e+00],
       [ 1.32967245e+00, -5.74052566e-01,  3.47354369e-01, ...,
        -5.83123916e-01,  1.74895780e+00, -1.09831140e+00],
       [-6.43766298e-01, -7.66087546e-01, -3.44500467e-01, ...,
        -5.83123916e-01, -5.71769086e-01,  9.10488596e-01],
       ...,
       [-2.70666889e-02,  4.82139824e-01,  1.38513662e+00, ...,
         1.71490137e+00, -5.71769086e-01,  9.10488596e-01],
       [-1.37352750e+00,  6.74174804e-01, -3.44500467e-01, ...,
        -5.83123916e-01,  1.74895780e+00,  9.10488596e-01],
       [-9.93229410e-01,  1.44231472e+00,  3.47354369e-01, ...,
         1.71490137e+00, -5.71769086e-01, -1.09831140e+00]])

In [56]:
import tensorflow as tf
from tensorflow import keras

In [57]:
from keras import Sequential
from keras.layers import Dense , Input

In [88]:
model= Sequential()
model.add(Input(shape=(11,)))
model.add(Dense(11, activation='relu'))
model.add(Dense(11, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [89]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [90]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [91]:
history=model.fit(xtrain_scaled , ytrain , epochs=20, validation_split=0.2)

Epoch 1/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7071 - loss: 0.5748 - val_accuracy: 0.7869 - val_loss: 0.4884
Epoch 2/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8127 - loss: 0.4490 - val_accuracy: 0.8044 - val_loss: 0.4464
Epoch 3/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8150 - loss: 0.4333 - val_accuracy: 0.8181 - val_loss: 0.4241
Epoch 4/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8273 - loss: 0.4001 - val_accuracy: 0.8325 - val_loss: 0.4059
Epoch 5/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8309 - loss: 0.4012 - val_accuracy: 0.8356 - val_loss: 0.3903
Epoch 6/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3850 - val_accuracy: 0.8456 - val_loss: 0.3765
Epoch 7/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8455 - loss: 0.3676 - val_accuracy: 0.8537 - val_loss: 0.3694
Epoch 8/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8464 - loss: 0.3678 - val_accuracy: 0.8500 - val_loss: 0.3660
Epoch 9/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8578 - loss: 0.3532 - val_accuracy: 0.8494 - val_loss: 0.3629
Epoch 10/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8538 - loss: 0.3472 - val_accuracy: 0.8506 - val_loss: 0.3617
Epoch 11/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8540 - loss: 0.3515 - val_accuracy: 0.8519 - val_loss: 0.3604
Epoch 12/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8503 - loss: 0.3515 - val_accuracy: 0.8500 - val_loss: 0.3584
Epoch 13/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8513 - loss: 0.3533 - val_accuracy: 0.8519 - val_loss: 0.3583
Epoch 14/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8487 - loss: 0.3594 - val_accuracy: 0.8537 - val_loss: 0.3562
Epoch 15/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8581 - loss: 0.3489 - val_accuracy: 0.8531 - val_loss: 0.3560
Epoch 16/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8528 - loss: 0.3489 - val_accuracy: 0.8506 - val_loss: 0.3560
Epoch 17/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8558 - loss: 0.3490 - val_accuracy: 0.8506 - val_loss: 0.3553
Epoch 18/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8565 - loss: 0.3411 - val_accuracy: 0.8494 - val_loss: 0.3565
Epoch 19/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8583 - loss: 0.3368 - val_accuracy: 0.8519 - val_loss: 0.3549
Epoch 20/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8595 - loss: 0.3429 - val_accuracy: 0.8512 - val_loss: 0.3541

In [92]:
model.layers[0].get_weights()

[array([[ 3.57926451e-02, -3.26054096e-01,  9.75018069e-02,
         -7.98336342e-02,  6.64339811e-02, -1.15455873e-01,
          2.69278735e-01, -2.28748456e-01,  2.57957101e-01,
         -2.36616395e-02,  2.69941568e-01],
        [ 6.96914867e-02, -1.15678944e-01,  1.24049366e-01,
         -7.95228541e-01, -8.60827923e-01, -2.36760247e-02,
         -1.81128368e-01,  1.95400566e-01,  4.31249738e-01,
          6.93338364e-02,  1.97355419e-01],
        [ 8.22786316e-02,  2.68381238e-01,  1.82533845e-01,
         -6.82363138e-02, -7.82666821e-03, -2.77605373e-02,
          4.39102769e-01, -1.02789894e-01,  3.06744315e-02,
          1.73877671e-01, -6.86953515e-02],
        [ 5.39514005e-01, -5.40127456e-01,  2.48109519e-01,
         -1.74929336e-01, -1.78040892e-01, -4.44426388e-01,
         -3.57295483e-01, -1.15312979e-01, -6.35810912e-01,
          1.58276483e-01, -3.85748707e-02],
        [-1.94712609e-01, -1.53048754e-01, -2.27742523e-01,
          1.12799227e-01, -3.92117101e-04,  9.94765878e-01,
          2.12052669e-02, -4.80998516e-01, -8.92325699e-01,
          9.39174294e-01,  1.82570338e-01],
        [ 2.91940480e-01, -9.22011584e-03,  1.00789033e-01,
         -1.02924958e-01, -1.37943521e-01,  5.74434362e-02,
          2.69302428e-01,  1.39634265e-02, -2.00802356e-01,
         -4.96828854e-02, -4.18411903e-02],
        [ 5.49411118e-01,  5.25812358e-02, -5.25261201e-02,
         -2.69730717e-01, -4.07286406e-01,  5.39208800e-02,
         -4.64580469e-02, -7.42571115e-01, -3.90627861e-01,
         -2.86729097e-01,  4.24562275e-01],
        [-3.36220004e-02, -5.52327454e-01,  3.49179804e-01,
         -8.88064280e-02, -1.10327806e-02, -8.56251568e-02,
          3.38103920e-01, -4.31366563e-01,  4.44467902e-01,
          6.34748563e-02,  1.10054627e-01],
        [-2.52307683e-01, -1.85970128e-01, -1.15669467e-01,
          2.16555923e-01, -2.59422064e-01,  3.22657615e-01,
         -6.01932526e-01,  5.78207552e-01, -4.49764449e-03,
         -1.77906334e-01, -5.93316793e-01],
        [ 4.41326886e-01,  5.10800600e-01, -3.65298510e-01,
         -2.98696399e-01,  1.05999388e-01, -9.07215476e-02,
          3.66227895e-01, -1.19105652e-01, -3.32988054e-02,
          3.16548467e-01, -1.47121876e-01],
        [ 9.07362998e-02,  3.68247211e-01,  6.33764744e-01,
         -1.87291324e-01,  5.13398945e-01,  1.12717025e-01,
         -4.92136925e-01, -1.32305712e-01,  2.51946807e-01,
          1.03873476e-01,  4.25444603e-01]], dtype=float32),
 array([ 0.19113202,  0.48315984,  0.19462676,  0.5175141 ,  0.4269812 ,
         0.16478468,  0.23883031, -0.07805653,  0.08883791, -0.25523278,
         0.22540312], dtype=float32)]

In [93]:
model.layers[1].get_weights()

[array([[ 0.23638739,  0.01868164,  0.4797867 ,  0.12186009,  0.21555078,
          0.6735227 ,  0.50704324, -0.3264453 , -0.01798687, -0.21583973,
          0.18129468],
        [-0.8337039 , -0.11061879,  0.29790962,  0.30523223, -0.2673914 ,
          0.3920338 , -0.63250804, -0.20854014,  0.5454343 , -0.1073347 ,
          0.35066473],
        [-0.34921038, -0.02547176,  0.39812055,  0.34774053, -0.21981598,
          0.07342323, -0.39491248,  0.4236834 , -0.22619492,  0.55911684,
          0.1703192 ],
        [-0.49158868,  0.5940735 ,  0.45596474,  0.06006064,  0.45492533,
         -0.04092629, -0.03282199,  0.14305821,  0.17436557, -0.3810444 ,
          0.20549294],
        [ 0.1466947 , -0.1486293 ,  0.62813747, -0.43936217,  0.30599952,
          0.41347057,  0.09637721, -0.00769419, -0.18928066, -0.5204865 ,
          0.26088977],
        [ 0.6694205 ,  0.2843708 ,  0.46482617, -0.49207494, -0.24833997,
          0.10272429,  0.6740318 ,  0.25013357,  0.32635763, -0.49544352,
         -0.29742062],
        [-0.25956693, -0.5109498 ,  0.3809529 , -1.1853392 , -0.05956489,
         -0.54844093, -0.24979906,  0.3869163 , -0.22547664,  0.48624566,
          0.05267529],
        [ 0.08903448,  0.01645149, -0.01208569,  0.21449995, -0.03429664,
         -0.26187447,  0.23637351,  0.19134746, -0.16343021,  0.5114463 ,
          0.4641897 ],
        [-0.47919068,  0.15090233, -0.41644806, -0.35723254,  0.3541008 ,
          0.349367  ,  0.05862095, -0.07974599,  0.22495879,  0.5979033 ,
          0.4914586 ],
        [ 0.8020737 , -0.29639873, -0.48744172, -0.38004032,  0.37910646,
         -0.183321  ,  0.6715803 , -0.38401908, -0.13913557, -0.30723342,
         -0.65591305],
        [ 0.1329431 , -0.5439616 ,  0.5546519 ,  0.4623399 ,  0.5580434 ,
         -0.02899263, -0.23264197,  0.06904373,  0.3538786 , -0.20731378,
         -0.26393813]], dtype=float32),
 array([-0.14858688,  0.19577774,  0.2766078 ,  0.07936443,  0.32668146,
         0.37915558, -0.06770676,  0.30148712,  0.1762228 , -0.03710954,
         0.04072675], dtype=float32)]

In [94]:
y_log=model.predict(xtest_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [95]:
y_pred=np.where(y_log>=0.5 , 1,0)

In [96]:
from sklearn.metrics import accuracy_score

In [97]:
accuracy_score(ytest , y_pred)

0.8505